- assets/js/account/account-dashboard.js
- assets/js/account/account-dashboard.tpl.liquid
- assets/js/account/account.js
- locales/en.default.json
- templates/customers/account.liquid
- templates/index.liquid
Demo is here: https://virtocommerce.atlassian.net/browse/VP-4693
> VP-4693: Add dashboard page, add redirect for logged user

- assets/js/account/account-checkout-defaults.js
- assets/js/account/account-checkout-defaults.tpl.liquid
- assets/js/account/account.js
- assets/js/checkout/checkout.js
Demo is here: https://virtocommerce.atlassian.net/browse/VP-4521
> VP-4521: Save user preferences (payment and shipping methods)

- assets/js/account/account-dashboard.tpl.liquid
- assets/scss/custom/_navs.scss
- assets/scss/custom/_type.scss
- snippets/dashboard/bulk-order-content.liquid
- snippets/main/header/nav.liquid
- snippets/main/header/nav/bulk-order-form.liquid
- snippets/shared/bulk-order-fields.liquid
+ add basic markup with placeholders for widgets
> VP-4651: Add bulk order widget to user dashboard

- assets/js/account/account-dashboard.tpl.liquid
- assets/js/account/account-last-orders-list.js
- assets/js/account/account-last-orders-list.tpl.liquid
- assets/js/account/account.js
- assets/scss/_custom.scss
- assets/scss/custom/_tables.scss
- assets/scss/custom/_text-decoration.scss
- assets/scss/custom/_type.scss
- locales/en.default.json
> VP-4634: Add 'Last orders' widget to user dashboard

- .github/workflows/main.yml
- Jenkinsfile
- assets/js/app/app.js
- assets/js/main.js
- layout/theme.liquid
- package-lock.json
- package.json
Depends on https://github.com/VirtoCommerce/vc-demo-storefront/pull/4
> VP-4238: Select default shipping address as default on checkout

- assets/js/account/account-last-orders-list.js
- assets/js/account/account-last-orders-list.tpl.liquid
> VP-4634: Remove link from invoice number

- assets/js/account/account-orders.tpl.liquid
- assets/scss/custom/_tables.scss
Columns width, borders, cell paddings were changed
> VP-4648: Style of the Order History table

- assets/js/account/account-dashboard.tpl.liquid
- assets/js/account/dashboard-user-list.js
- assets/js/account/dashboard-user-list.tpl.liquid
- locales/en.default.json
> VP-4635: Add users widget to dashboard

- assets/js/account/account-company-members.js
> VP-4847: Fix pagination behaviour on company members page

- assets/js/product.js
- snippets/dialogs/recently-added-cart-item.liquid
> VP-4745: Add correct link for product in recently-added-items dialog

- assets/js/account/account-dashboard.tpl.liquid
- assets/scss/custom/_grid.scss
- assets/scss/custom/_panels.scss
> VP-4852: Fix gutters on dashboard layout

- assets/js/account/account-lists.js
- assets/js/account/account-lists.tpl.liquid
> VP-4287: Disable 'Add to cart' button at unavailable and sold out cases

- assets/js/common-components/address.tpl.html.liquid
Also, address validation fixed (allow use + at the start, i.e. both 12345676890 and +1234567890 are valid)
> VP-4804: Save phone on new address form

- assets/js/checkout/checkout.js
- assets/scss/custom/_buttons.scss
- snippets/collection/main.liquid
- templates/cart.liquid
Temporary changes required for categoryt page incapsulated into specific class and this class added to category layout
> VP-4624: Fix purchase order number style & notification

- assets/scss/custom/_type.scss
> VP-4643: Fix font error

- assets/js/product-compare/add-to-compare-checkbox.js
- assets/js/product-compare/product-compare-list-bar.js
- assets/js/product-compare/product-compare-list-bar.tpl.html.liquid
- assets/js/product-compare/product-compare.js
- assets/scss/modules/_vc-compare.scss
- snippets/collection/main.liquid
- templates/product-compare.liquid
> VP-4976: Fix compare products behaviour

- assets/scss/custom/_buttons.scss
Add to cart button hover style fix
> VP-4643: Add to cart button hover style fix

- assets/js/account/account-orders-status-stats.js
- assets/js/account/account-orders-status-stats.tpl.liquid
> VP-4961: Change order statuses on stats widget

- assets/js/account/account.js
> VP-4876: Fix error at '/orders' page reloading

- assets/js/account/account-checkout-defaults.js
> VP-4876: Fix data loading on 'CHECKOUT DEFAULTS' page

- assets/js/app/app.js
- assets/js/product.js
- assets/scss/custom/_grid.scss
- snippets/product/main.liquid
- snippets/product/quantity.liquid
- snippets/product/variations-panel.liquid
For calculations used Banker's rounding as in .NET
Added basic validation for qty input
*also fix broken variations layout
> VP-5106: Recalculate totals for configurable product

- assets/scss/custom/_buttons.scss
- snippets/product/grid-item.liquid
- snippets/product/quantity-grid.liquid
> VP-5291: Change layout for configurable product card

- assets/js/account/account-orders.tpl.liquid
> VP-5197: Show order status on order details page

- assets/js/account/account-orders.js
- assets/js/common-components/lineItems.js
- assets/js/common-components/lineItems.tpl.liquid
> VP-5146: Add item to cart from order details

- assets/js/lists/lists-added-list-item-dialog.liquid
- assets/js/lists/lists-create-new-list-dialog.liquid
- assets/js/lists/lists-settings-dialog.liquid
- assets/scss/_custom.scss
- assets/scss/custom/_type.scss
- snippets/dialogs/recently-added-cart-item.liquid
- snippets/dialogs/select-fulfillment-center.liquid
- snippets/dialogs/send-cart-to-email.liquid
- snippets/dialogs/send-product-to-email.liquid
- snippets/dialogs/sign-in-to-proceed.liquid
- snippets/error_popup.liquid
- templates/cart.liquid
> VP-5317: Fix modal headers, pickup method title, address title wrapping

- assets/js/account/account-company-members.js
- assets/js/account/account-company-members.tpl.liquid
- assets/js/common-components/labeled-textarea.js
- assets/js/common-components/labeled-textarea.tpl.html.liquid
- assets/scss/_helpers.scss
- assets/scss/custom/_forms.scss
- locales/en.default.json
Demonstration video is here:
virtocommerce.atlassian.net/browse/VP-3950
> VP-3950: Apply role to invited members

- assets/js/product.js
- snippets/product/grid-item.liquid
- snippets/product/price.liquid
- templates/product.liquid
Price should be the same on the product and on the category pages
> VP-5277: Fix the error with the wrong price of configurable product on the category page

- snippets/dialogs/send-cart-to-email.liquid
> VP-5317: Correct style for the Email modal header

- assets/js/checkout/checkout-configurable-line-item.js
- assets/js/checkout/checkout-configurable-line-item.tpl.html.liquid
- assets/js/checkout/checkout-line-item.tpl.html.liquid
- assets/js/checkout/checkout.js
- assets/js/product.js
- assets/scss/_helpers.scss
- assets/scss/custom/_grid.scss
- assets/scss/custom/_panels.scss
- assets/scss/custom/_tables.scss
- assets/scss/custom/_type.scss
- templates/cart.liquid
> VP-5396: Display configurable product in cart

- assets/js/cart.js
- assets/js/checkout/checkout.js
- assets/js/common-components/totals.tpl.liquid
- assets/js/services.js
- assets/scss/_variables.scss
- assets/scss/custom/_grid.scss
- assets/scss/custom/_panels.scss
- locales/en.default.json
- templates/cart.liquid
Demo video is here:
https://virtocommerce.atlassian.net/browse/VP-5052
> VP-5052: Add 'promotion code' functionality

- assets/js/checkout/checkout-configurable-line-item.tpl.html.liquid
> VP-4987: Remove link from title of configurable line item

- assets/js/checkout/checkout.js
demo is here:
https://virtocommerce.atlassian.net/browse/VP-5052
> VP-5052: Fix disappearance of coupon when switching to another page

- assets/js/account/account-orders.js
- assets/js/account/account-orders.tpl.liquid
- assets/js/common-components/lineItems.tpl.liquid
- assets/js/product.js
> VP-5568: Show dialog when product's inventory is limited after reorder

- assets/js/account/account-orders.tpl.liquid
- assets/js/checkout/checkout-configurable-line-item.js
- assets/js/checkout/checkout-configurable-line-item.tpl.html.liquid
- assets/js/checkout/checkout.js
- assets/js/common-components/lineItems.js
- assets/js/common-components/lineItems.tpl.liquid
- assets/js/product.js
- assets/scss/_custom.scss
- assets/scss/custom/_tables.scss
- snippets/dialogs/recently-added-cart-item.liquid
- templates/cart.liquid
> VP-5696: Prepare theme for storefront changes (cart and order details)

- assets/js/common-components/relatedProducts.js
- assets/js/common-components/relatedProducts.tpl.html.liquid
- assets/scss/_variables.scss
- assets/scss/modules/_owl-carousel.scss
- snippets/dialogs/recently-added-cart-item.liquid
- templates/cart.liquid
Also fixed image size in related products to prevent disproportions
> VP-5749: Change dialogs size

- assets/js/checkout/checkout.js
- assets/js/checkout/dialogs/checkout-select-payment-method.js
- assets/js/checkout/dialogs/checkout-select-shipment-method.js
- assets/scss/_custom.scss
- assets/scss/_helpers.scss
- assets/scss/custom/_buttons.scss
- assets/scss/custom/_forms.scss
- assets/scss/custom/_tables.scss
- templates/cart.liquid
Also fixed behaviour and responsivness of payment method popup, fixed layout for address popup according to design.
Demo in comments: https://virtocommerce.atlassian.net/browse/VP-5599
> VP-5599: Implement the redesign for the select shipping method dialog

- .github/workflows/main.yml
Added the ability to release alpha version artifacts when manually trigger main CI workflow from any branch
> VP-6007: Merge main and release-alpha

- assets/scss/bootstrap-migration/_default-variables.scss
- assets/scss/bootstrap-migration/_maps.scss
- config/blocks_schema.json
- templates/blocks/helpers/block-inner-paddings.liquid
- templates/blocks/helpers/block-margins.liquid
- templates/blocks/helpers/block-paddings.liquid
- templates/blocks/helpers/block-title.liquid
- templates/blocks/helpers/cover-text.liquid
- templates/blocks/helpers/hide-criteria.liquid
- templates/blocks/json-buy-now-search.liquid
- templates/blocks/json-buy-now.liquid
- templates/blocks/json-call-to-action.liquid
- templates/blocks/json-cover-with-form.liquid
- templates/blocks/json-cover-with-image-and-flexible-title.liquid
- templates/blocks/json-cover-with-image.liquid
- templates/blocks/json-cover-with-simple-text.liquid
- templates/blocks/json-features-with-icons-in-columns.liquid
- templates/blocks/json-features-with-icons.liquid
- templates/blocks/json-headline-with-form.liquid
- templates/blocks/json-headline.liquid
- templates/blocks/json-logotypes.liquid
- templates/blocks/json-product-tiles.liquid
- templates/blocks/json-text.liquid
- templates/blocks/json-two-columns-text.liquid
- templates/index.liquid
- templates/json-page.liquid
- templates/json-preview.liquid
Demo in comments: https://virtocommerce.atlassian.net/browse/VDS-408
> VDS-408,VDS-348: Migrate 'Cover with image' block

- assets/scss/_variables.scss
- assets/scss/custom/_navs.scss
- assets/scss/custom/_scaffolding.scss
- templates/cart.liquid
Video in comments: https://virtocommerce.atlassian.net/browse/VDS-461
> VDS-461: Rework navigation process on checkout

- assets/scss/bootstrap-migration/_variables.scss
- assets/scss/bootstrap-migration/override/_scaffolding.scss
- snippets/bootstrap-migration/shared/breadcrumb.liquid
- snippets/bootstrap-migration/shared/bulk-order-fields.liquid
- templates/404.liquid
- templates/bulk-order.liquid
- templates/customers/confirm_invitation.liquid
- templates/error.liquid
- templates/lockedout.liquid
- templates/product-compare.liquid
> VDS-392: Migrate bulk-order, product-compare, error and 404 pages to bootstrap 4

- assets/js/checkout/checkout.js
> VDS-58: Fix error.  Cart icon not updated on Complete page of the checkout 

- assets/js/account/account-password-change.js
- assets/js/account/account-password-change.tpl.liquid
> VDS-74:  Fix error with chaging user password

- assets/js/lists/lists-added-list-item-dialog.liquid
- snippets/bootstrap-migration/main/header/top.liquid
- snippets/customers/badge.liquid
- snippets/main/header/top.liquid
Test case: 
Click to "lists" link in the top header.
Result
Page with user lists.
> VDS-109: Correct all links to user lists

- assets/js/common-components/totals.js
- assets/js/common-components/totals.tpl.liquid
> VDS-54: Fix error. Shipping method isn't updated on Order Summary

- assets/js/app/app.js
- assets/js/checkout/checkout-configurable-line-item.tpl.html.liquid
- assets/js/checkout/checkout-line-item.tpl.html.liquid
- assets/js/controllers/product-card/common-product-card.js
- assets/js/controllers/product/configurable-product.js
- assets/js/directives/integer.js
- assets/js/directives/only-integer.js
- snippets/product/quantity.liquid
- snippets/product/type/configured/quantity.liquid
Also disable add to cart button if qty = 0
> VDS-200, VDS-79: Fix errors with invalid input qty values

- assets/js/checkout/checkout.js
- templates/cart.liquid
> VDS-34: Implement "Purchase order number" cleaning button

- assets/js/collection.js
- snippets/collection/sidebar/applied-filters.liquid
> VDS-70: Fix error. catalog - filters - id instead of text when select branch availability

- assets/js/account/account-orders.js
> VDS-99: Fix error. It is possible to pay an order using a credit card for non "Purchased agent" role

- assets/js/account/dashboard-user-list.tpl.liquid
> Fix broken localization on dashboard page

- snippets/product/list-item.liquid
> VDS-52, VDS-692: Fix error.  Add to Cart from list view doesn't work.

- assets/js/checkout/checkout-configurable-line-item.tpl.html.liquid
- assets/js/checkout/checkout-line-item.tpl.html.liquid
- snippets/product/type/common/product-delivery.liquid
- templates/customers/account.liquid
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.9.0-pr-171.zip
> VDS-746: Hide subscriptions from B2B-theme

- assets/js/controllers/dialogs/add-to-cart.js
- assets/js/controllers/product/product-with-variations.js
- assets/js/services.js
- locales/en.default.json
- snippets/dialogs/recently-added-cart-item.liquid
- snippets/product/price.liquid
- snippets/product/price/dynamic.liquid
- snippets/product/type/with-variations/product-title-info.liquid
- snippets/product/type/with-variations/product.liquid
- snippets/product/variations-panel.liquid
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.9.0-pr-172.zip
> VDS-688: Implement ability of the bulk adding variations to the cart 

- assets/js/checkout/checkout-configurable-line-item.js
- assets/js/checkout/checkout-configurable-line-item.tpl.html.liquid
- assets/js/common-components/lineItems.js
- assets/js/common-components/lineItems.tpl.liquid
- assets/js/controllers/product-card/configurable-product-card.js
- assets/js/controllers/product/configurable-product.js
- snippets/product/product-configuration-list.liquid
- snippets/product/type/configured/item-price.liquid
- snippets/product/type/configured/product.liquid
- templates/product.liquid
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.9.0-pr-173.zip
> VDS-800: Integrate configurable products backend with theme

- locales/en.default.json
- snippets/collection/sidebar.liquid
- snippets/collection/sidebar/previously-purchased.liquid
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.10.0-pr-175.zip
> VDS-855: Add 'View purchased products' block to category sidebar

- .editorconfig
- assets/js/controllers/price.js
- assets/js/services/searchQuery.js
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.10.0-pr-176.zip
> VDS-654, VDS-857: Fix price error and pagination issue

- .github/workflows/autotest.yml
Reverts VirtoCommerce/vc-demo-theme-b2b#179
> Revert "VP-6710: Create Theme workflow to run UI autotests"

- assets/js/common-components/address.tpl.html.liquid
- assets/js/common-components/lineItems.js
- assets/js/common-components/lineItems.tpl.liquid
- assets/scss/_helpers.scss
- assets/scss/custom/_buttons.scss
- assets/scss/custom/_panels.scss
- assets/scss/custom/_type.scss
- locales/en.default.json
- templates/cart.liquid
QA-test: VDS-1047
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.11.0-pr-185-5852923d.zip
> VDS-861: Update UI for 3rd step of checkout

- assets/js/account/b4/account-orders-list.tpl.liquid
Description: 
--
QA-test: VDS-1089
Demo-test: 
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.12.0-pr-190-33ab5ef8.zip
> VDS-1116: Remove 'table-responsive' class from order history page table

- assets/js/account/account-order-detail.tpl.liquid
- assets/js/account/account-orders.js
Description: 
--
QA-test: VDS-1126
Demo-test: 
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.12.0-pr-191-a4693b6f.zip
> VDS-1090: Implement Simple reorder of a completed order 

- .github/workflows/deploy-pr.yml
- test.deploy
Description: 
--
QA-test: VDS-412
Demo-test:  VDS-413
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.13.0-pr-196-bcb9b9eb.zip
> VDS-414: test

- .github/workflows/deploy-pr.yml
- .github/workflows/main.yml
Description: 
Switch actions to master version
--
QA-test: VDS-412
Demo-test: VDS-413
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.13.0-pr-200-d6b49c8e.zip
> VDS-414: Switch actions to master version

- .github/workflows/autotest.yml
Description: 
Added Katalon e2e tests autorun on PR to dev or master branch for Demo Solution
--
QA-test: 
Demo-test: 
Download artifact URL:
> VDS-572: Add Katalon e2e tests autorun on PR

- .github/workflows/deploy-pr.yml
- .github/workflows/main.yml
Description: 
SonarCloud didn`t get the artifact version to determine "old" and "new" code to create issues
--
QA-test: 
Demo-test: 
Download artifact URL:
> VP-7344: Fix sonarcloud didnt get version number
